### ISSUE TITLE
Bug: xticklabels overwrites xminorticks setting

### ISSUE THREAD

**Issue by syrte** [proplot-dev/proplot#428]
### Description

xticklabels overwrites xminorticks setting

### Steps to reproduce

Expected behavior with minorticks
```python
fig, ax = pplt.subplot()
ax.format(
    xticks=[0, 0.5, 1], #xticklabels=['a', 'b', 'c'],
    xminorticks=[0.1, 0.2],
)
```
![image](https://github.com/proplot-dev/proplot/assets/7038335/29137c1c-45e4-4e31-b40b-011349a1d4b8)

But I got this if setting `xticklabels`
```
fig, ax = pplt.subplot()
ax.format(
    xticks=[0, 0.5, 1], xticklabels=['a', 'b', 'c'],
    xminorticks=[0.1, 0.2],
)
```
![image](https://github.com/proplot-dev/proplot/assets/7038335/a2dc8915-162c-47e7-9e92-eb171a49fe17)

minorticks are gone...

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)` here.
3.4.3
0.9.5.post341

**Comment by syrte** [comment]
Temporary workaround:
Set minor ticks manually after calling ax.format,
```
ax.set_xticks(tick_list, minor=True)
```

**Comment by lukelbd** [comment]
Thanks for the report. Setting minor ticks after major ticks seems to work too:

```python
fig, ax = pplt.subplot()
ax.format(xticks=[0, 0.5, 1], xticklabels=['a', 'b', 'c'])
ax.format(xminorticks=[0.1, 0.2])
```

![iTerm2 F1OMIJ tmp7n9dxpt3](https://github.com/proplot-dev/proplot/assets/19657652/efdb97c0-62cb-4041-a12a-5437c2904cf6)

**Comment by lukelbd** [comment]
This was due to a `format()` convenience feature: By default, if you pass major ticks labels, minor ticks are disabled, since it's pretty rare that users need both and since proplot changes the default matplotlib style to include minor ticks. This makes the process of setting up manual tick labels take 1 step instead of 2.

However, this should clearly be disabled if a `minorlocator` is passed in the same call. Fixed by https://github.com/proplot-dev/proplot/commit/a397f81746c6f4e1a97e605f3f6957ef7baeeec4.
